name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install TexLive dependecies
        run: |
          sudo apt update
          sudo apt install texlive texlive-bibtex-extra texlive-extra-utils texlive-font-utils texlive-lang-german texlive-latex-extra texlive-plain-generic texlive-science latexmk
      - name: Compile LaTeX document
        run: |
          latexmk document.tex -interaction=nonstopmode -file-line-error -pdf
      - name: Upload Thesis Artifact
        uses: actions/upload-artifact@master
        with:
          name: Thesis
          path: document.pdf
